export const PUSH_PREVIOUS_PATH = "PUSH_PREVIOUS_PATH"
export const POP_PREVIOUS_PATH = "POP_PREVIOUS_PATH"
export const SET_PROGRESS = "SET_PROGRESS"
export const SET_START_ANIMATION = "SET_START_ANIMATION"